// GENERATED CODE - DO NOT MODIFY BY HAND
// This file is manually created to provide Hive adapters for aggregated_metrics.dart
// In a normal build, this would be generated by hive_generator with build_runner.

part of 'aggregated_metrics.dart';

// Note: The adapters are defined in lib/storage/hive_adapters.dart
// This file exists only to satisfy the 'part' directive in aggregated_metrics.dart.
